// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFRjsEHsxkA1LbJ3FU5XQWt9dw9RyP72E',
    appId: '1:1075187934729:web:fbec4680d3cb30d6327ad8',
    messagingSenderId: '1075187934729',
    projectId: 'liggo-pi-3a2a4',
    authDomain: 'liggo-pi-3a2a4.firebaseapp.com',
    storageBucket: 'liggo-pi-3a2a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADzxVwJ5yLc1WPNhznUoDb5oEbZpVa7gs',
    appId: '1:1075187934729:android:a21446b5b646ca4c327ad8',
    messagingSenderId: '1075187934729',
    projectId: 'liggo-pi-3a2a4',
    storageBucket: 'liggo-pi-3a2a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxenyMeBZ76u5MP7o6n0_XBGVtqT1Bp9g',
    appId: '1:1075187934729:ios:ef266fdd01b59760327ad8',
    messagingSenderId: '1075187934729',
    projectId: 'liggo-pi-3a2a4',
    storageBucket: 'liggo-pi-3a2a4.firebasestorage.app',
    iosClientId: '1075187934729-hir5re33jcloore8mnj93ghnh94835r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.liggoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxenyMeBZ76u5MP7o6n0_XBGVtqT1Bp9g',
    appId: '1:1075187934729:ios:ef266fdd01b59760327ad8',
    messagingSenderId: '1075187934729',
    projectId: 'liggo-pi-3a2a4',
    storageBucket: 'liggo-pi-3a2a4.firebasestorage.app',
    iosClientId: '1075187934729-hir5re33jcloore8mnj93ghnh94835r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.liggoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTFG2r5GOFgxLH43233iY0Q7bP0TZ3Iz4',
    appId: '1:1075187934729:web:f955cb7283f4a534327ad8',
    messagingSenderId: '1075187934729',
    projectId: 'liggo-pi-3a2a4',
    authDomain: 'liggo-pi-3a2a4.firebaseapp.com',
    storageBucket: 'liggo-pi-3a2a4.firebasestorage.app',
  );
}
